/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientRouteRouteImport } from './routes/$client/route'
import { Route as ClientIndexRouteImport } from './routes/$client/index'
import { Route as ClientEntrarRouteImport } from './routes/$client/entrar'

const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/$client',
  path: '/$client',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientEntrarRoute = ClientEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => ClientRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$client': typeof ClientRouteRouteWithChildren
  '/$client/entrar': typeof ClientEntrarRoute
  '/$client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/$client/entrar': typeof ClientEntrarRoute
  '/$client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$client': typeof ClientRouteRouteWithChildren
  '/$client/entrar': typeof ClientEntrarRoute
  '/$client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$client' | '/$client/entrar' | '/$client/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$client/entrar' | '/$client'
  id: '__root__' | '/$client' | '/$client/entrar' | '/$client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$client': {
      id: '/$client'
      path: '/$client'
      fullPath: '/$client'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$client/': {
      id: '/$client/'
      path: '/'
      fullPath: '/$client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/$client/entrar': {
      id: '/$client/entrar'
      path: '/entrar'
      fullPath: '/$client/entrar'
      preLoaderRoute: typeof ClientEntrarRouteImport
      parentRoute: typeof ClientRouteRoute
    }
  }
}

interface ClientRouteRouteChildren {
  ClientEntrarRoute: typeof ClientEntrarRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientEntrarRoute: ClientEntrarRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ClientRouteRoute: ClientRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
